# Generated by Django 4.2.17 on 2024-12-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('1', 'FOOD'), ('2', 'CLOTH')], default='1', max_length=9)),
            ],
        ),
    ]
